url: https://latmarat.github.io
baseurl: "" #/agency-jekyll-theme/

# Site settings
title: Marat I. Latypov
email: marat.latypov@georgiatech-metz.fr
description: "Homepage of Marat I. Latypov - Materials Scientist at Georgia Tech Lorraine, previously with POSTECH. Research interests: materials informatics and data sciences, multiscale modeling, microstructures, and advanced steels."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
# people:
# - name: Kay Garland
  # pic: 1
  # position: Lead Designer
  # social:
    # - title: twitter
      # url: #
    # - title: facebook
      # url: #
    # - title: stack-overflow
      # url: #

# - name: Larry Parker
  # pic: 2
  # position: Lead Marketer
  # social:
    # - title: twitter
      # url: #
    # - title: facebook
      # url: #
    # - title: linkedin
      # url: #

# - name: Diana Petersen
  # pic: 3
  # position: Lead Developer
  # social:
    # - title: twitter
      # url: #
    # - title: facebook
      # url: #
    # - title: google-plus
      # url: #

# Social networks links
social:
  - title: linkedin
    url: http://kr.linkedin.com/in/latmarat
  - title: github
    url: http://github.com/latmarat
academic:
  - title: mendeley
    url: https://www.mendeley.com/profiles/marat-latypov/
  - title: orcid
    url: http://orcid.org/0000-0003-4416-0877
  - title: researchgate
    url: https://www.researchgate.net/profile/Marat_Latypov
  - title: google-scholar
    url: https://scholar.google.com/citations?user=We5aJywAAAAJ&hl=en&oi=ao

google_analytics: UA-61278008-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
